{
 "title": "Rightsizing demo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(namespace, container, pod) (\n  sum by(namespace, pod) (\n    rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=~\"$namespace\"}[30m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Greedy namespaces",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (\n      (\n          rate(\n            container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[30m]\n          )\n        - on(namespace, pod, container) group_left()\n          avg by(namespace, pod, container) (\n            kube_pod_container_resource_requests{resource=\"cpu\"}\n          )\n      ) * -1 > 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Greedy namespaces",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (\n      (\n          rate(container_memory_usage_bytes{container!=\"POD\",container!=\"\"}[30m])\n        - on(namespace, pod, container) group_left()\n          avg by(namespace, pod, container) (\n            kube_pod_container_resource_requests{resource=\"memory\"}\n          )\n      ) * -1 > 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(namespace, container, pod) (\n  sum by(namespace, pod) (\n    container_memory_usage_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers without CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by (namespace)(sum by (namespace,pod,container)(kube_pod_container_info{container!=\"\", namespace=~\"$namespace\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers without CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "count by (namespace)(sum by (namespace,pod,container)(kube_pod_container_info{container!=\"\", namespace=~\"$namespace\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers without Memory Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count by (namespace)(sum by (namespace,pod,container)(kube_pod_container_info{container!=\"\", namespace=~\"$namespace\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers without Memory Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "count by (namespace)(sum by (namespace,pod,container)(kube_pod_container_info{container!=\"\", namespace=~\"$namespace\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers CPU Oversized",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(namespace, container, pod) (\n    (\n        rate(\n            container_cpu_usage_seconds_total{\n                container!=\"POD\",\n                container!=\"\",\n                namespace=~\"$namespace\"\n            }[30m]\n        )\n        - on(namespace, pod, container) group_left()\n        avg by(namespace, pod, container) (\n            kube_pod_container_resource_requests{\n                resource=\"cpu\",\n                namespace=~\"$namespace\"\n            }\n        )\n    ) * -1 > 0\n)\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Memory Oversized",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace, container, pod) (\n    (\n        \n            container_memory_usage_bytes{\n                container!=\"POD\",\n                container!=\"\",\n                namespace=~\"$namespace\"\n            }\n        - on(namespace, pod, container) group_left()\n        avg by(namespace, pod, container) (\n            kube_pod_container_resource_requests{\n                resource=\"memory\",\n            }\n        )\n    ) * -1 > 0\n)\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU use by workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(workload) (\n  sum by(namespace, pod) (\n    rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=~\"$namespace\"}[30m])\n  ) * on(namespace, pod) group_left(workload)\n  label_replace(kube_pod_info, \"workload\", \"$1\", \"created_by_name\", \"(.*)\")\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average memory use by workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(workload) (\n  sum by(namespace, pod) (\n    container_memory_usage_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\"}\n  ) * on(namespace, pod) group_left(workload)\n  label_replace(kube_pod_info, \"workload\", \"$1\", \"created_by_name\", \"(.*)\")\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}